// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AmbassadorCountController from "./ambassador_count_controller"
application.register("ambassador-count", AmbassadorCountController)

import CampaignCancelController from "./campaign_cancel_controller"
application.register("campaign-cancel", CampaignCancelController)

import ChangePositionController from "./change_position_controller"
application.register("change-position", ChangePositionController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImageInputController from "./image_input_controller"
application.register("image-input", ImageInputController)
